codecov:
  branch: migration
comment:
  layout: header, changes, diff, sunburst
coverage:
  precision: 2
  round: down
  range: "60...95"
  ignore:
  - Demo/*
  status:
    patch:
      default:
        target: auto
    project:
      default:
        target: auto
