use_frameworks!

target "NUIDemo" do
  pod "NUIParse"
end

target "NUITests" do
  pod 'FBSnapshotTestCase', :git => 'https://github.com/broadwaylamb/ios-snapshot-test-case.git', :branch => 'swift3-beta-6'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
