source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target "NUIDemo" do
  pod "NUIParse"
end

target "NUITests" do
  pod 'FBSnapshotTestCase'
  pod 'UIImage+ColorFromImage'
end
