use_frameworks!

target "NUIDemo" do
  pod "NUIParse"
end

target "NUITests" do
  pod 'FBSnapshotTestCase', :git => 'https://github.com/broadwaylamb/ios-snapshot-test-case.git', :branch => 'swift-3-beta-4'
  pod 'UIImage+ColorFromImage'
end
